apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  labels:
    app: ai-agent

spec:
  replicas: 1
  revisionHistoryLimit: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: ai-agent

  template:
    metadata:
      labels:
        app: ai-agent

    spec:
      containers:
        - name: ai-agent
          image: 416573464919.dkr.ecr.us-east-1.amazonaws.com/ai-agent:v321
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            # =============================
            # GROQ
            # =============================
            - name: GROQ_API_KEY
              value: "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"

            # =============================
            # SNOWFLAKE SECRETS
            # =============================
            - name: SNOWFLAKE_USER
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: SNOWFLAKE_USER

            - name: SNOWFLAKE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: SNOWFLAKE_PASSWORD

            - name: SNOWFLAKE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: SNOWFLAKE_ACCOUNT

            - name: SNOWFLAKE_WAREHOUSE
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: SNOWFLAKE_WAREHOUSE

            - name: SNOWFLAKE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: SNOWFLAKE_DATABASE

            - name: SNOWFLAKE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: SNOWFLAKE_SCHEMA

            - name: SNOWFLAKE_ROLE
              valueFrom:
                secretKeyRef:
                  name: snowflake-secret
                  key: SNOWFLAKE_ROLE

            # =============================
            # FLAGS
            # =============================
            - name: ENABLE_RAG
              value: "false"

          # =============================
          # HEALTH CHECKS
          # =============================
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          # =============================
          # FREE TIER OPTIMIZED
          # =============================
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "150m"